### ISSUE TITLE
[CH07] AWS EKS에 Secret Manager에 등록된 시크릿 주입하기

### ISSUE THREAD

**Issue by CJ0823** [room-of-coding/backend-deep-dive#4]
# Secret CSI Driver
(또는 AWS Secrets and Configuration Provider, ASCP 사용가능)
AWS에서 Secret Manager의 값을 k8s Secret으로 주입할 수 있는 드라이버

선결조건:
- EKS 노드의 IAM 역할에 Secret Manager에 연결할 수 있는 정책 설정

다음 명령어로 Secrets CSI Drvier 설치
```shell
kubectl apply -k "github.com/aws/secrets-store-csi-driver-provider-aws/deployment/base?ref=main"
```

# SecretProviderClass 설정
Secret Manager의 값들을 k8s에 마운트하기 위해 SecretProviderClass 리소스를 만들고 주입
## SecretProviderClass 설정
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
#       secret manager에서 정의한 key 이름과 타입. MyDatabaseSecret 내부에 
#       {"username": "admin", "password": "mypassword"}와 같은 형태로 secret들이 들어있는 형태로 생각하면 됨
      - objectName: "MyDatabaseSecret" 
        objectType: "secretsmanager"
```

## Secret 주입
기존 k8s에서 주입하듯이 볼륨을 설정하고 주입하면 됨. 다만 볼륨을 만들 때 csi.driver 항목을 추가하여 아래처럼 넣어주면 됨
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: my-app-image
    volumeMounts:
    - name: secret-volume
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: secret-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "my-aws-secrets"
```
